### ISSUE TITLE
Possibly to record voice or upload an mp3 to be speaked instead of TTS Voice

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#185] opened 2022-11-14 10:00 UTC
Many users have requested us the possibility to add one/two new action/s that allow to play, instead of TTS voice, a record voice (live record) or an mp3 file uploaded to the communicator. In case of on-air record voice it could be neccesary to use the device microphone to make a live record (perhaps limited to 30 seconds for example to avoid heavy files) and in case of uploading an mp3 limited to a size less than.... (what you consider better).

**Comment by klues** [comment] 2022-11-15 09:03
I'm closing this because it's a duplicate of https://github.com/asterics/AsTeRICS-Grid/issues/22

**Closed by klues** 2022-11-15 09:03 UTC
