### ISSUE TITLE
Cells with "Speak custom text" must speak custom text when accumulated phrase is readed. 

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#182] opened 2022-11-10 12:04 UTC
Cells with custom text should speak the custom text when reading the accumulated sentence instead of the label text (showing the label text under the symbols as now).

**Comment by mjtc1985** [comment] 2023-04-29 08:28
Hello, I opened a pull request #265 to try to solve this issue.

**Comment by klues** [comment] 2023-05-03 07:44
Great, thanks! 👍 
I think the first issue that is fixed by an external contributor 🎉 

I've merged the PR and released it to https://grid.asterics.eu/latest/
@arasaac-dga please test there and give your feedback.

Priority of speaking (in mode "speak separately") is now:
1. Recorded audio, if available
2. Text from "speak custom text", if available
3. Fixed grammar by your API, if available
4. Normal label of the element

In mode "speak continiously" recorded audio isn't used.

**Comment by arasaac-dga** [comment] 2023-05-03 11:46
We have tested it and it works great except when "automatic grammar correction" is activated in Spanish. In this case as you can see in the attached video there is a problem with custom text that is distributed in the consecutive cells (one word per cell) deleting the correct text of each cell. If you continue pressing the Play button the problem is increased. 

https://app.box.com/s/0zqe2o3t2d0fpk4kuvojeauudffgftn1

**Comment by klues** [comment] 2023-05-04 14:34
I've released this to main version with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-05-04-16.18%2F%2B0200 since we wanted to release the new application language romanian.

Since the issue is only related to the automatic grammar correction (which isn't released yet), we'll have to fix it before releasing https://github.com/asterics/AsTeRICS-Grid/issues/242 to main version. It's still for testing in `latest` version

**Comment by klues** [comment] 2023-05-31 08:02
I think it would be most consistent for cells with custom text that the custom text is also shown within the collect element like this:
![grafik](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/ae08e4ac-b2ce-47bd-9db7-69f19af62898)

@arasaac-dga what do you think?

**Comment by klues** [comment] 2023-05-31 08:39
Please test the current version at https://grid.asterics.eu/latest/

The issue with distributing words across cells should be fixed, however I've tested the example from your video and your API returns: `YO NECESITO DESCANSO MUCHO PARA ESTAR MUY FUERTE` which I think (or at least ChatGPT thinks) is not correct: 

![grafik](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/eb0ea10c-9859-46e2-ada8-8a5b01114000)

And "TÚ QUIERO" again results in "TÚ QUIERO" - I think this was already correct at some time and resulted in "TÚ QUIERES"?!

**Comment by arasaac-dga** [comment] 2023-05-31 10:06
We have tested and works fine and the issue shown in the video attached at the beginning is solved with the same example. Only we have detected with the same example that when you play several times, for example, in the third one change "NECESITO DESCANSO" that is correct by "NECESITO DESCANSAMOS" (that is not correct) and in fourth ("NECESITO DESCANSAR") (that is correct too).

https://github.com/asterics/AsTeRICS-Grid/assets/82500056/bdcf81fb-a824-4e0b-b78b-7d29ee000536

As we see it is a problem in our API (we have replied to it in our API). So, launch it to main and we check  and solve all the errors that appear on our part with the API.

**Comment by klues** [comment] 2023-05-31 11:44
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-05-31-13.40%2F%2B0200

**Closed by klues** 2023-05-31 11:44 UTC
Labels: good first issue

**Comment by arasaac-dga** [comment] 2023-05-31 11:54
Thanks. We have solved the problem. It was a problem in service that control the API on server that needed a reset ;-)

**Comment by arasaac-dga** [comment] 2023-05-31 12:26
No "Tu quiero" is not correct. It would be "Tú quieres". ChatGPT know very good spanish and he tries to offer the most correct phrase. So our phrase is correct although always there are other possibilities more used, for example. Anyway, we are going to monitorize everything and receive feedback of users that sure will help to improve our API. Thanks

**Comment by klues** [comment] 2023-05-31 12:28
Yes, I know, but I receive "tu quiero" from your API:

![image](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/c189ca4a-c0bc-4d53-a4c7-f40eea7f40bf)

**Comment by arasaac-dga** [comment] 2023-05-31 13:49
Yes. This is because "QUIERO" is conjugated and is third person (not first person as YO. We will add a exception in our API to handle this with users that have QUIERO instead of QUERER (the inifinitive) and we will send you by email a new backup in Spanish of ARASAAC Global Communicator in which he have changed QUIERO by QUERER. Thanks.
