### ISSUE TITLE
Uncaught (in promise) ReferenceError: audioUtil is not defined

### ISSUE THREAD

**Issue by juan-angel** [asterics/AsTeRICS-Grid#329] opened 2023-10-08 09:33 UTC
Hi.

Since I updated to the latest version y get the following error whenever I try to play a recorded audio:
![error](https://github.com/asterics/AsTeRICS-Grid/assets/15798955/6c6d24df-b832-41da-991d-355cf1c1a80b)

I've tested in Firefox and Chromium and the issue seems to be happening in both browsers.

BTW, I really appreciate your work. It's helping my son to communicate. Thanks.

**Comment by deinhofer** [comment] 2023-10-09 06:33
Dear Juan, thank you for filing the issue. It is a duplicate of #326 and was already fixed. It should be released soon.

**Closed by deinhofer** 2023-10-09 06:33 UTC

**Comment by juan-angel** [comment] 2023-10-09 11:09
Done. It works like a charm 😊

Thank you so much.

**Comment by klues** [comment] 2023-10-12 13:50
released to main version with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-10-12-15.47%2F%2B0200
