### ISSUE TITLE
Customize cells: frame color or not

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#306] opened 2023-06-12 16:48 UTC
Add an option in the settings page to define if you want to color the cell background or the cell frame according to Fitzgerald or Goosens key (or predefined color). In case of selecting colour the frame the cell background will be the default selected. In the case of colouring the cell frame it would be neccesary to have an option to set the frame width (more or less thick).

**Comment by klues** [comment] 2023-06-30 08:55
duplicate of https://github.com/asterics/AsTeRICS-Grid/issues/259 - I'll add your comment for the details there.

**Closed by klues** 2023-06-30 08:55 UTC
Labels: good first issue
